services:
  - type: web
    name: thiruvizha
    runtime: node
    buildCommand: npm install --prefix server && npm install --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    healthCheckPath: /api/health